# Generated by Django 5.2.17 on 2026-09-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('confirmacion', 'Confirmación de reserva'), ('recordatorio_24h', 'Recordatorio 24 h antes'), ('cancelacion', 'Cancelación de reserva')], max_length=20)),
                ('enviado', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, help_text='Último error de envío, si lo hubo.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'notificación',
                'verbose_name_plural': 'notificaciones',
                'ordering': ['-creado_en'],
            },
        ),
    ]
