# Generated by Django 5.2.17 on 2026-09-06 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notificaciones', '0001_initial'),
        ('reservas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='reservas.reserva'),
        ),
        migrations.AddConstraint(
            model_name='notificacion',
            constraint=models.UniqueConstraint(fields=('reserva', 'tipo'), name='notificacion_unica_por_tipo_y_reserva'),
        ),
    ]
