# Generated by Django 5.2.17 on 2026-09-06 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0001_initial'),
        ('reservas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='reservas.reserva'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['pendiente', 'aprobado'])), fields=('reserva', 'tipo'), name='pago_activo_unico_por_tipo_y_reserva'),
        ),
    ]
