# Generated by Django 5.2.17 on 2026-09-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoFecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('motivo', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'bloqueo de fecha',
                'verbose_name_plural': 'bloqueos de fecha',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='ReglaDisponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'verbose_name': 'regla de disponibilidad',
                'verbose_name_plural': 'reglas de disponibilidad',
                'ordering': ['espacio', 'dia_semana', 'hora_inicio'],
            },
        ),
    ]
