# Generated by Django 5.2.17 on 2026-09-06 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disponibilidad', '0001_initial'),
        ('salones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloqueofecha',
            name='espacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='salones.espacio'),
        ),
        migrations.AddField(
            model_name='regladisponibilidad',
            name='espacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_disponibilidad', to='salones.espacio'),
        ),
        migrations.AddConstraint(
            model_name='bloqueofecha',
            constraint=models.CheckConstraint(condition=models.Q(('inicio__lt', models.F('fin'))), name='bloqueo_inicio_antes_de_fin'),
        ),
        migrations.AddConstraint(
            model_name='regladisponibilidad',
            constraint=models.CheckConstraint(condition=models.Q(('hora_inicio__lt', models.F('hora_fin'))), name='regla_hora_inicio_antes_de_fin'),
        ),
    ]
