# Generated by Django 5.2.17 on 2026-09-06 01:21

import apps.reservas.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0002_initial'),
        ('salones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='espacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='salones.espacio'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['espacio', 'inicio'], name='reservas_re_espacio_5e7172_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['estado'], name='reservas_re_estado_7c17e1_idx'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('inicio__lt', models.F('fin'))), name='reserva_inicio_antes_de_fin'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('monto_total__gte', 0)), name='reserva_monto_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('estado__in', ['pendiente', 'confirmada'])), expressions=[('espacio', '='), (apps.reservas.models.TsTzRange('inicio', 'fin', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&')], name='reserva_sin_solapamiento_por_espacio'),
        ),
    ]
