# Generated by Django 5.2.17 on 2026-09-06 01:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('capacidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_base', models.DecimalField(decimal_places=2, help_text='Precio de referencia. El monto final de la reserva puede diferir.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'espacio',
                'verbose_name_plural': 'espacios',
                'ordering': ['salon__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('direccion', models.CharField(max_length=255, verbose_name='dirección')),
                ('politica_cancelacion_horas', models.PositiveIntegerField(default=48, help_text='Antelación mínima para cancelar una reserva sin penalidad.', verbose_name='horas mínimas para cancelar')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'salón',
                'verbose_name_plural': 'salones',
                'ordering': ['nombre'],
            },
        ),
    ]
