# Generated by Django 5.2.17 on 2026-09-06 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'rol': 'admin_salon'}, on_delete=django.db.models.deletion.CASCADE, related_name='salones', to=settings.AUTH_USER_MODEL, verbose_name='propietario'),
        ),
        migrations.AddField(
            model_name='espacio',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacios', to='salones.salon', verbose_name='salón'),
        ),
        migrations.AddConstraint(
            model_name='espacio',
            constraint=models.UniqueConstraint(fields=('salon', 'nombre'), name='espacio_nombre_unico_por_salon'),
        ),
    ]
